baseURL = "https://karll0s.github.io/meu-blog/"
languageCode = "pt-br"
title = "Simples Nerd"
theme = "PaperMod"

enableEmoji = true

[params]
  description = "ğŸ’»ğŸ§ Um cantinho simples onde compartilho coisas sobre Linux, tecnologia e tudo mais que desperta minha curiosidade nerd."

  defaultTheme = "auto"
  disableThemeToggle = false

  ShowReadingTime = true
  ShowShareButtons = true
  ShowCodeCopyButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowToc = true

  env = "production"

  [params.homeInfoParams]
    Title = "ğŸ‘‹ OlÃ¡, eu sou o Simples Nerd"
    Content = """
ğŸ’¡ Bem-vindo ao **Simples Nerd**!

Aqui eu escrevo de forma simples e direta sobre:
- ğŸ§ **Linux**
- ğŸ§  **Tecnologia**
- ğŸ› ï¸ **Experimentos, dicas e curiosidades**
- ğŸ® E outras coisas nerds que me interessam

Sinta-se em casa â˜•
"""

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "Sobre"
    url = "/sobre/"
    weight = 2
